### ISSUE TITLE
Add ability to specify the timezone the date should be displayed in

### ISSUE THREAD

**Issue by mdjnelson** [mdjnelson/moodle-mod_customcert#145]
We may have a user in Italy who wants the date to display in English, but due to their timezone it will display in Italian.

**Comment by michael-milette** [comment]
It doesn't make sense to have the language dependant on the time zone. What about countries and cities where people speak multiple languages? I also can't see how there could be a connection between timezone and language.

I just tested it and, changing the Moodle language does indeed change the language in which the date is displayed.

If this isn't happening for you, the problem may be that the required language pack is not installed in your operating system.

In Moodle, calendars and dates often get their text from the operating system. In order to have the date appear in English, you may need to install the English language pack to your operating system. For example, in Ubuntu, you would use the following commands at a shell terminal prompt:

    sudo apt-get install language-pack-en
    sudo service apache2 reload

The "en" is the ISO 639-1 two letter language code. You can find a list of these by going to:
https://en.wikipedia.org/wiki/ISO_639-1

For example, if the problem is actually that the language is displaying only in English and you need it in Italian, you will need to install the Italian language pack:

    sudo apt-get install language-pack-it
    sudo service apache2 reload

You can test to see if the language pack was properly installed by using the following command:

    sudo locale -a

If this command shows that the language pack is installed but it is still not working for you, you may need to restart the operating system for the changes to take effect.

If you are using a different operating system than Ubuntu, please check your operating system's documentation on how to complete a similar procedure.

Hope this helps.

Best regards,

Michael Milette

**Comment by mdjnelson** [comment]
Thanks Michael, appreciated. Closing this issue.
