### ISSUE TITLE
Warn users about the potential to bulk email an empty certificate before it is ready

### ISSUE THREAD

**Issue by Jarvil** [mdjnelson/moodle-mod_customcert#276]
Hello,

Please consider changing the way "Email students" setting works at the moment, it emails the copy of the certificate to the students when you enable and in my opinion it shoudn't do this automatically since it is very easy to users to miss the instructions "if set this will email the students of copy of the certificate when it becomes available".

This way it's easy for a teacher to create a certificate on a course -> set the email students on -> suddenly everyone on the course gets and cerfiticate even when it wasn't the teacher intent. After that 100 students will have a certificate that isn't valid.

**Comment by Jarvil** [comment]
It should email the copy of the certificate to the student only when he/she opens it. If you want to bulk email certificates to students of the course you could add a tab which lets you do single or bulk actions.

**Comment by Markibacsi** [comment]
@Jarvil 

I had the same problem. But if you setup the course without adding any students, then add a restriction to the certificate activty (date or grade works for me). 

Then, when you add the students, they won't get a certificate straight away.

Plus - you can use the course as a template for other new courses :)

**Comment by Jarvil** [comment]
Hello,

I know but it would still want to see the default behavior of "email students" to be changed.

**Comment by markn86** [comment]
> It should email the copy of the certificate to the student only when he/she opens it. If you want to bulk email certificates to students of the course you could add a tab which lets you do single or bulk actions.

I disagree with this. The whole point of the functionality was because teachers were claiming after a student passed the course they did not bother viewing the certificate, and then never got it. Then when it got time to verify the certificate it was too late. If we wait until the student views the certificate then we may as well remove the emailing functionality altogether.

**Comment by Jarvil** [comment]
By trusting that the teacher understands that adding a certificate-activity to a course will automatically/instantly deliver the certificate the all students on a course is quite a bold way to think when you think about "normal end users" who don't usually graps how things work technically or have the patience to find out.

**Comment by markn86** [comment]
I am up for suggestions, but having the email only send when the users clicks on the certificate is not the right approach as it is the sole reason this setting was introduced (numerous people requested due to their users not bothering to click on it).

Perhaps a warning next to the form element letting the user know that it could result in unintentional mass emails if not set-up correctly.

**Comment by Jarvil** [comment]
Any suggestion is good as long as certificate isn't delivered automatically to all course participants when certifcate without a access restriction is created on a course.

**Comment by mdjnelson** [comment]
I updated the lang string and added some logic in the email certificate task so it doesnt send emails for certificates that have no elements.
