### ISSUE TITLE
Multi-language filter is not applied

### ISSUE THREAD

**Issue by mohamedmohamedatia** [mdjnelson/moodle-mod_customcert#292]
In the Verify Page, the title appears like 

> {mlang ar}مهارات{mlang}{mlang en}Maharat{mlang}

. which means the multilang filter is not applied

![image](https://user-images.githubusercontent.com/30835105/59762048-f4240480-929e-11e9-9280-53fd33ee5278.png)

**Comment by markn86** [comment]
Thanks for the report. I will fix this in the next release.

**Comment by WaylanderPK** [comment]
Does this also affect the subject line of emails? (seems to be the case on our site).

```
Date: Thu, 19 Sep 2019 at 16:16
Subject: LE5 Drug Tester Certified Operator Test: {mlang en} Alcolizer LE5 Drug Tester Operator Certificate of Competency{mlang}{mlang vi} Alcolizer LE5 Trình kiểm tra ma túy Chứng chỉ năng lực{mlang}{mlang zh_cn} Alcolizer LE5药物测试员操作能力证书{mlang}
```

**Comment by markn86** [comment]
Yep, looks like that is another spot that is suffering. Thanks.

**Comment by markn86** [comment]
I could not get the multi-language filter to work when using `{mlang ar}مهارات{mlang}{mlang en}Maharat{mlang}` but when I tried with `<span class="multilang" lang="en">En: group</span><span class="multilang" lang="ru">Ru: group</span>` it worked fine - is there something I am missing in order to get the `mlang` tags to work?

**Comment by mohamedmohamedatia** [comment]
You have to turn the multilang filter on from this path 

Site administration/ Plugins /Filters/ Manage filters

make sure to select from Apply to both heading and content

**Comment by markn86** [comment]
Thanks Mohamed.

I did indeed do this.

See -

<img width="693" alt="mlang_no_filter" src="https://user-images.githubusercontent.com/783213/66422784-3dd95c00-ea02-11e9-885e-67d686522548.png">

The `En: group` text is from the description of the certificate which was `<span class="multilang" lang="en">En: group</span><span class="multilang" lang="ru">Ru: group</span>` so that is filtered correctly. The screenshot is taken from the page `mod/customcert/view.php`. Does the name of the certificate filter for you correctly on this page?

**Comment by mohamedmohamedatia** [comment]
For me, it shows correctly in both Arabic and English 
Check the below screenshots from both Arabic and English 

![image](https://user-images.githubusercontent.com/30835105/66453955-dc030b80-ea6e-11e9-9ea3-576f6b1cc240.png)


![image](https://user-images.githubusercontent.com/30835105/66454025-1371b800-ea6f-11e9-88f1-f3a34c8cdf61.png)

**Comment by mohamedmohamedatia** [comment]
Also, I checked again the verify page and notice the following 

when the URL contains the contextid Like this URL it works normally check the first 2 screenshots  
https://maharat.tu.edu.sa/mod/customcert/verify_certificate.php?contextid=3310387

but when the URL does not contain the contextid it doesn't work check the last screenshot


![image](https://user-images.githubusercontent.com/30835105/66454255-fdb0c280-ea6f-11e9-8517-43a3bb46597a.png)

![image](https://user-images.githubusercontent.com/30835105/66454382-61d38680-ea70-11e9-83f0-3b0b3e1a3868.png)


Below screenshot without contextid 

![image](https://user-images.githubusercontent.com/30835105/66454182-b75b6380-ea6f-11e9-82dc-81c36665da0c.png)

**Comment by mdjnelson** [comment]
Hi Mohamed,

I believe you must be using https://moodle.org/plugins/filter_multilang2 to use the `mlang` syntax and I am not able to replicate it.

Closing.
