### ISSUE TITLE
Date element contain rare text 

### ISSUE THREAD

**Issue by AdrianHernandezG** [mdjnelson/moodle-mod_customcert#296]
Hello! I installed this great plugin last week, but I have a problem with the "date" element. Once I configure my custom certificate, I try the "Save changes and preview" button: the certificate is correctly downloaded, but when I preview it, the "date" element always shows the text "Example date:" text before the real date.

![cert 2](https://user-images.githubusercontent.com/32368591/60218316-92324480-9834-11e9-9fb2-80aab6bfaac3.JPG)

**Comment by markn86** [comment]
Hi Adrian,

That will not be shown to students who download the certificate. It is only shown in the preview mode. If you visit the course, click on the certificate and download an issue for yourself you will see it is not listed there. The reason it was added was because people were getting confused. The preview mode does not attempt to do any logic and just shows the current date regardless of the settings - this meant I was getting a lot of issues being reported about the date element displaying the wrong date, when in fact it was it was just because the preview mode was showing the current date.

**Comment by markn86** [comment]
I'll keep this open and am up for suggestions on how to address both these problems.
