### ISSUE TITLE
No images after course backup/restore

### ISSUE THREAD

**Issue by zozo77** [mdjnelson/moodle-mod_customcert#298]
After I did backup and restore of the course, background image of the certificate disappeared. I had to manually edit the certificate, load template that was already loaded and save certificate again. That's not a big issue if you do manual backup/restore but if you want to automate the process for large number of courses, for example using web services API course duplicate function, this becomes the big issue. We used Moodle online courses on our university to generate certificate of completion for our classroom short courses. So we made a Moodle course as a template that we want to duplicate using web services API for each offline course that we have. A lot of courses generates a lot of manual work. 
Any help in resolving the issue would be appreciated. I know this involves some programming. Author of the plugin would do it easily I suppose. I'm not a hardcore programmer but with some directions from experienced Moodle developer, maybe I could help as well. 
Kind regards,
Zoran

**Comment by markn86** [comment]
Are these the replication steps?

1. Create a course.
2. Create a custom certificate.
3. Add a background image.
4. Backup/restore
5. Restore to another course
6. Backup image is missing

OR was a template involved to initially load the certificate and then that was backed up?

**Comment by zozo77** [comment]
These are the replication steps:

Create a course
Create a custom certificate
Load certificate template that includes background image
Save the certificate
View certificate, backup image is there
Backup the course
Restore to the new course
View certificate, backup image is missing

**Comment by zozo77** [comment]
I can confirm that the same issue exists when using duplicate course web servicesa API function instead of course backup/restore procedure.
I can also confirm that the same issue exists when copying the activity within the same course. 
So the reproduction steps can be:

1. Create a course
2. Create a custom certificate
3. Load certificate template that includes background image
4. Save the certificate
5. View certificate, backup image is there
6. Duplicate the course using web services API function core_course_duplicate_course
7. Open duplicated course
8. View certificate, backup image is missing

...or:

1. Create a course
2. Create a custom certificate
3. Load certificate template that includes background image
4. Save the certificate
5. View certificate, backup image is there
6. Duplicate the custom certificate activity
7. Open duplicated custom certificate activity
8. View certificate, backup image is missing

**Comment by markn86** [comment]
I have a feeling #107 is related, but need to investigate further when I get time.

**Comment by emmarichardson** [comment]
This also happens if you create the certificate from scratch, not using a template.  All fields come across with the exception of the background image.  Could this maybe be a permissions issue - could it be that the backup restore is not able to access the images folder?  It is a big issue for us now.  Now that we can reference course fields, I can actually add credit hours to the course and use a default certificate in my template course without having a different image for each specific number of credit hours.  But the inability to copy a certificate with the backup image basically makes this feature worthless because my course creator has to manually add the image or load a template every time they create the new course.

**Comment by Markibacsi** [comment]
@emmarichardson 
We use the certificate activity as part of a course template, and have not encountered this problem at all! I have a collection of templates for the different courses we offer.

It may be worth noting, that we create new courses using the bulk upload (CSV) process. We simply have a field in the file called 'templatecourse' and the relevant short name of the template course. This method has returned zero errors (so far) and I can create 100 courses in about 10 minutes - depending on the size of the template course.

Hope this helps :)

**Comment by emmarichardson** [comment]
I use the course template plugin to create courses and this happens every time.  I specifically tested yesterday with a certificate that was not created using a template to see if that was a workaround but to no avail.  I know that the course upload uses a slightly different process to the backup/restore process (for example, activity dates do not adjust with course upload as they do with backup restore).  I use my site for event management and having an easy way to duplicate a course is vital in the workflow.  Course upload would be far beyond my course creator, unfortunately…I was really excited when I saw that we could pull custom course fields so that I could add credit hours automatically but with the picture not pulling, it defeats the whole process.

Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

**Comment by emmarichardson** [comment]
Have you had a chance to look at this at all?  I looked at 107 and I guess that would make sense if that was related...not a coder (just know enough to be dangerous!!) but would be happy to help in testing or anything else...

**Comment by mdjnelson** [comment]
I have added this to my to-do list.

**Comment by emmarichardson** [comment]
Thanks!

**Comment by mdjnelson** [comment]
So, when you load a template any image is just pointing to the system images you added in the template. Then, when you make a backup it doesnt include the images as they are system images. This backup when restored on another site for example will not include the images. I am basically writing a patch to copy the images to the module context rather than just pointing to the system ones.

**Comment by emmarichardson** [comment]
That makes sense - thank you so much for getting to this.  I know a lot of people will appreciate it.

Emma

**Comment by mdjnelson** [comment]
Created a fix.

It copies the site files to the course context then refers to them instead of site. You can still however choose a site image to display if you want.

This will be available in next release.
