### ISSUE TITLE
No Permissions to do that...

### ISSUE THREAD

**Issue by summerhousetraining** [mdjnelson/moodle-mod_customcert#384]
Hi Everyone

I have a functioning Moodle 3.9.2 (Build: 20200914) hosted on shared infrastructure provided by SiteGround.

This morning I have installed from the plugings menu 'Custom certificate' (mod_customcert) version 3.8.4 (2019111804) which I can't seem to access. 

I am site administrator and have all permissions showing as 'Yes'.

When selecting Site Administration > Plugins > Custom Certificate > Manage templates - I receive an error message stating: _'Sorry, but you do not currently have permissions to do that (Manage a custom certificate)'_

I can click the links for verify certificate or image upload and they work fine.

I have logged out and back in, same issue. - Anyone else have the same issue, or am I missing something?

Thanks all,

Stewart
![Screenshot 2020-10-14 at 11 44 01](https://user-images.githubusercontent.com/72863736/95978907-bc858800-0e12-11eb-8010-e531b91af141.png)

**Comment by mdjnelson** [comment]
Hm, yes strange this would happen to a site administrator. Since I have not heard of this happening before I think it must be a configuration issue on your site with permissions (though I may be wrong). Have you looked at the permissions for `mod/customcert:manage`? Are any roles prohibited from doing this that you may be assigned at a lower level?
