### ISSUE TITLE
Support SVG as Background

### ISSUE THREAD

**Issue by tea2go** [mdjnelson/moodle-mod_customcert#409]
Is it possible or is it planned to use SVG files as certificate background at some point?
I often have problems with pixelated elements as a result of JPEG or PNG formats😥

**Comment by mdjnelson** [comment]
I just set up a PDF with a .svg icon as the background and it worked as expected. What version of the plugin are you running?

The image I used was a random one I found on the internet - https://cdn.shopify.com/s/files/1/0496/1029/files/Freesample.svg.

**Comment by mdjnelson** [comment]
What version of Moodle and the plugin are you running?

**Comment by TheRialD** [comment]
it supports it, but when generating the certificate it shows the issue

**Comment by TheRialD** [comment]
in my case I got an all black screen

**Comment by shivan** [comment]
Same here. Is there a solution?
Preview is correct. But when generating the PDF, it is a black page. Only one text is shown, as this is green.

That's how it's configured:
![image](https://github.com/mdjnelson/moodle-mod_customcert/assets/1827692/19e86e4f-62e4-44e5-992e-d79d4c61b35b)

Only these 3 items.

**Comment by mdjnelson** [comment]
Are one of you able to provide me with the `.svg` you used? Either attach the image here or If you don't want it to be public you can email me at mdjnelson@gmail.com and will test it there, if that's still not an option ill have to find a `.svg` on the net that has an issue because I can't replicate it with the `.svg` I used.

**Comment by shivan** [comment]
I now bought Affinity Designer 2 and opened the svg there - and in my case it also was black. Having a deeper look, I saw that there was a black rectangle which caused the blackness, so I could fix it by myself in this case. I think that was a bug of the old version of affinity designer, since I exported it there previously.

**Comment by mdjnelson** [comment]
Thanks for the update. I am closing this as I can't replicate it and if it was a very common issue I suspect there would be way more people complaining. Also, displaying the .svg is done by the TCPDF library so if it was an issue it would be something I couldnt change in my plugin.
