### ISSUE TITLE
Moodle 4.0 | PHP 7.4 Strange behavior when building a template

### ISSUE THREAD

**Issue by gemguardian** [mdjnelson/moodle-mod_customcert#500]
Hi Mark, 
i having an issue while building a template with a background image. 
For some reasons the background image is moving "out" of the field while adding new elements to the template. 

I have created a video to show you what happens. I am thinking it is a css class that is not acting as it should but I am not sure. 
https://vimeo.com/714380853

Hope you can solve this puzzle for me. 
Thank you
Gemma

**Comment by Sunoyon** [comment]
I am facing similar issue for version 4.0. Can anyone be kind enough to solve this issue?

**Comment by alihamas575** [comment]
I have the same problem, I supported the subject with images to explain a little more in detail. However, although the same problem has been opened before, the solution is still not found, which scared me a little.

Obviously I use this plugin very often, I need to solve this problem,

I am running an education service ([temel isg eğitimi](https://www.halimasa.com.tr/temel-isg-egitimi)) that is legally compulsory in the laws of the country through my website. Our businesses with the definition of [bursa osgb](https://www.halimasa.com.tr/bursa-osgb-firmalari) Companies are established and managed with an official document called OHS Services regulation.

**Comment by mdjnelson** [comment]
Linking #513 to this.

**Comment by alihamas575** [comment]
Hello @mdjnelson ,  will there be an update on this topic?  I don't know exactly how it works in moodle developer part.  Isn't there any voluntary development here?  Do you stop development because you stopped working at moodle?  There are many people who need help with this, just like me.  Can you help us?

**Comment by baris83** [comment]
Found out that in boost theme the tiny scrollbar on the right of the page  causing the problem. I've added a line of css code and now working as expected. 

`#page-mod-customcert-rearrange #page.drawers {
  overflow-y: initial;
}`

**Comment by alihamas575** [comment]
Hello Mr. Barış,
how did you solve this problem did you do a manual update?

Or is this problem fixed in the new update of moodle?

**Comment by baris83** [comment]
Oh sorry, i've a custom child theme based on boost theme, but you can also add that css line to "Site administration > Appearance > Additional HTML" "Within HEAD"  section. But this time wrap it with style tag as shown below. Remember to purge cache after adding that line. Hope this helps
`<style>#page-mod-customcert-rearrange #page.drawers { overflow-y: initial; }</style>`

**Comment by abautu** [comment]
> Oh sorry, i've a custom child theme based on boost theme, but you can also add that css line to "Site administration > Appearance > Additional HTML" "Within HEAD" section. But this time wrap it with style tag as shown below. Remember to purge cache after adding that line. Hope this helps `<style>#page-mod-customcert-rearrange #page.drawers { overflow-y: initial; }</style>`

This did now work for me.

**Comment by abautu** [comment]
I found the problem to be created by the two issues:
- JS code caches the X,Y coordinated of the #pdf element; however sometimes the coordinates of the #pdf element change (for example, when user closes some notification), but the JS is not updated; Since the certificate elements (including background) are positioned absoluted, they will overlap other parts of the page.
- The YUI getX, getY function return different values when scrolling the page.

You can see these issues here: https://user-images.githubusercontent.com/4072355/205483443-c8a2c7a4-3434-4767-8987-ccd8dc9bcde0.mp4

This patch fixes the problem: 
[customcert_layout_fix.patch.txt](https://github.com/mdjnelson/moodle-mod_customcert/files/10148174/customcert_layout_fix.patch.txt)

I tested this in Moodle 4.0.5 and with this fix everything work correct (ref #495).

**Comment by mdjnelson** [comment]
Pulled in @abautu patch and pushed, releasing in plugins DB now.
