### ISSUE TITLE
Adding a Monologo

### ISSUE THREAD

**Issue by matthiasAtFernUni** [mdjnelson/moodle-mod_customcert#568]
Could you please add a moodle 4 monologo?

**Comment by danowar2k** [comment]
We'd like one, too.

**Comment by danowar2k** [comment]
Also necessary: The function in lib.php with which the colors for the activity icon are determined (FEATURE_MOD_PURPOSE)

**Comment by mdjnelson** [comment]
Sorry I am out of the loop on this one. Not sure what a mono logo is (remember I don't work at Moodle anymore and just try and keep this up-to-date in free time). I am happy to look at a peer review or code change. Thanks!

**Comment by mdjnelson** [comment]
Please see https://moodle.org/mod/forum/discuss.php?d=455203.

**Comment by mwreichel** [comment]
Hi,
we created for our moodle installations a monologo for mod_customcert for 4.0 as well as for the further change with 4.4.
I'm not used doing a pull request in github, but I'd like to share both with you, so that the new icons will be available.

FYI: Up to 4.3 it was necessary to have the monologo as SVG and PNG, with 4.4 the new monologo is only used as SVG, therefore a general change with this version would be necessary?!

All the best,
Martin

[monologo_mod_customcert_4.0.zip](https://github.com/mdjnelson/moodle-mod_customcert/files/15413069/monologo_mod_customcert_4.0.zip)
[monologo_mod_customcert_4.4.zip](https://github.com/mdjnelson/moodle-mod_customcert/files/15413072/monologo_mod_customcert_4.4.zip)

**Comment by mdjnelson** [comment]
Not sure if ill need a new branch, cause it must just ignore it but still work. Ill test.

**Comment by mdjnelson** [comment]
Ah, looks like it will.

**Comment by mdjnelson** [comment]
Done. Need to fix a few things now since I created two new branches for 4.3 and 4.4 (I was delaying this as long as possible). Behat is failing in 4.4 for whatever reason but the icons have been cherry-picked. I authored them as "Martin W. Reichel <martin.w.reichel@univie.ac.at>". Thanks!

**Comment by mdjnelson** [comment]
Forgot to set `FEATURE_MOD_PURPOSE`, done now. :)

**Comment by danowar2k** [comment]
Hello! The monologo.svg file seems to be "bad" somehow? Github displays it alright, but something is in the SVG code that

* makes programs like Intellij display just a black box (see image)
![image](https://github.com/user-attachments/assets/a26e6b33-bf5c-4ba1-a9c5-f5e6a03fe530)
* displays the monologo in black in Moodle when it should be white (see image)
![image](https://github.com/user-attachments/assets/3f794cca-db19-4ccb-9bb8-e514152a2641)

I can't read SVG yet, so I don't know what's happening there (maybe a black background or layer or something?)

Other monologos without this problem:
* https://github.com/learnweb/moodle-mod_ratingallocate/blob/v4.0-r1/pix/monologo.svg
* https://github.com/moodle/moodle/blob/MOODLE_401_STABLE/mod/assign/pix/monologo.svg

**Comment by danowar2k** [comment]
The screenshot contained our own monologo. I reverted it to using only yours. Sadly, same result for now:

![image](https://github.com/user-attachments/assets/52fe6f6f-136e-4044-9703-90449fc05f34)

**Comment by danowar2k** [comment]
Removing the monologo.svg file reverts the background to white (while using our monologo).

I'll upload that here...
![monologo](https://github.com/user-attachments/assets/f2d72d37-22e9-4447-adb2-43cd2c9f9bae)

**Comment by danowar2k** [comment]
Sorry, ignore the previous posts. The reason that the monologo has gone black with us was that before you had no monologo and no MOD_PURPOSE set in the plugin. So the purpose of the activity was set to "other".

And that led to an automatic white background that and the black icon because the icon color is determined by the background color.

We use theme_boost_union where we can reassign MOD_PURPOSE for activities but even if we reassigned it, the black color was forced. So we decided which color the activity would have and added a CSS rule that reverted Moodle's decision to have it black so that the icon was forced to be white.

But now MOD_PURPOSE is set, and Moodle's decision would make the icon white. So the CSS rule inverted the white decision and made it black.

So...nothing to see here, sorry.
